

```{r setup}
library(here)
library(dplyr)
library(RSocrata)
library(stringr)

# load data
raw_analyst_data <- 
  read.socrata("https://data.oregon.gov/Revenue-Expense/Salaries-of-State-Agencies-Multi-Year-Report/4cmg-5yp4") %>% 
  filter(
    str_detect(classification, regex("analyst", ignore_case = TRUE)),
    full_part_time == "FULL TIME",
    fiscal_year == last(fiscal_year)
  )

# Function to remove numbers from text and get unique values
clean_list_of_names <- function(text) {
  # Split text into separate roles if comma-separated
  roles <- unlist(strsplit(text, ","))
  # Remove numbers and trim whitespace
  cleaned_roles <- 
    gsub("[0-9]", "", roles) %>% 
    trimws(.) %>% 
    stringr::str_to_title(.)
  
  # Count frequencies and sort
  role_freq <- table(cleaned_roles)
  sorted_roles <- names(sort(role_freq, decreasing = TRUE))
  
  # Combine back into comma-separated string
  paste(sorted_roles, collapse = "\n")
}
```

```{r}
analyst_salary_data <- 
  raw_analyst_data %>% 
  rename(
    Year = fiscal_year,
    Agency = agency_title,
    Role = classification,
    Salary= annual_salary,
    Agency_no = agency
  ) %>% 
  group_by(Agency, Year) %>% 
  mutate(total_analysts = n()) %>% 
  mutate(
    Agency = if_else(total_analysts < 11, "Multiple Agencies", Agency),
    cleaned_roles = clean_list_of_names(Role)
  ) %>% 
  reframe(
    average_analyst_salary = round(median(Salary), -1),
    total_analysts = median(total_analysts),
    types_of_analysts = first(cleaned_roles)
  ) %>% 
  arrange(-total_analysts) %>% 
  relocate(Year, types_of_analysts)

analyst_salary_data
```


```{r}
write.csv(analyst_salary_data, here("save", "analyst_salary_data.csv"))
dput(analyst_salary_data %>% as.data.frame())
```

I used this data with Shiny assistant to then create an interactive viz. The result of that session is the *app.R* file in the */shiny/* folder. 